const searchList = [
  'Wall Street New York City',
  'One World Trade Center and 9/11 Memorial New York City',
  'Battery Park New York City',
  'Governors Island New York City',
  'Statue of Liberty New York City',
  'Ellis Island New York City',
  "St Paul's Chapel New York City",
  'South Street Seaport New York City',
  'Brooklyn Bridge New York City',
  'Civic Center New York City',
  'Museum at Eldridge Street New York City',
  'Chinatown New York City',
  'Little Italy and Nolita New York City',
  'Lower East Side Tenement Museum New York City',
  'TriBeCa New York City',
  'SoHo Historic District New York City',
  'East Village New York City',
  'Washington Square New York City',
  'Greenwich Village New York City',
  'Whitney Museum of American Art New York City',
  'The High Line New York City',
  'Union Square New York City',
  'Flatiron Building New York City',
  'Madison Square New York City',
  'Empire State Building New York City',
  'Herald Square New York City',
  'Times Square New York City',
  'The New York Public Library New York City',
  'Morgan Library & Museum New York City',
  'Grand Central Terminal New York City',
  'United Nations New York City',
  'Rockefeller Center New York City',
  "St. Patrick's Cathedral New York City",
  'Museum of Modern Art New York City',
  'Fifth Avenue New York City',
  'A Tour of Central Park New York City',
  'Intrepid Sea, Air & Space Museum New York City',
  'The Met Breuer New York City',
  'The Frick Collection New York City',
  'The Metropolitan Museum of Art New York City',
  'The Solomon R. Guggenheim Museum New York City',
  'American Museum of Natural History New York City',
  'Lincoln Center New York City',
  'Columbia University New York City',
  'Harlem New York City',
  'The Bronx New York City',
  'The Cloisters New York City',
  'Brooklyn New York City',
  'Jones Beach State Park New York State',
  'The Hamptons & Montauk New York State',
  'Hudson River Valley New York State',
  'Albany New York State',
  'Saratoga Springs New York State',
  'Adirondack Mountains New York State',
  'Cooperstown New York State',
  'Finger Lakes New York State',
  'Syracuse New York State',
  'Rochester New York State',
  'Chautauqua New York State',
  'Buffalo New York State',
  'Niagara Falls New York State',
  'Princeton New Jersey',
  'Atlantic City New Jersey',
  'Cape May New Jersey',
  'Independence Hall Philadelphia',
  'Second Bank of the United States Philadelphia',
  'US Mint Philadelphia',
  'Independence Seaport Museum Philadelphia',
  'Reading Terminal Market Philadelphia',
  'Masonic Temple Philadelphia',
  'Pennsylvania Academy of Fine Arts Philadelphia',
  'College of Physicians of Philadelphia/Mütter Museum Philadelphia',
  'Eastern State Penitentiary Philadelphia',
  'Philadelphia Zoo Philadelphia',
  'Fairmount Park Philadelphia',
  'Philadelphia Museum of Art Philadelphia',
  'The Barnes Foundation Philadelphia',
  'Gettysburg Pennsylvania',
  'Lancaster Pennsylvania',
  'Hershey Pennsylvania',
  'York Pennsylvania',
  'Reading Pennsylvania',
  'Longwood Gardens Pennsylvania',
  'Pittsburgh Pennsylvania',
  'Laurel Highlands Pennsylvania',
  'Western Amish Country Pennsylvania',
  'Beacon Hill Boston',
  'Black Heritage Trail Boston',
  'Boston Common & Public Garden Boston',
  'Boston Athenaeum Boston',
  'The Freedom Trail Boston',
  'Massachusetts State House Boston',
  'Park Street Church Boston',
  'Downtown Crossing Boston',
  'Theater District Boston',
  'Chinatown Boston',
  'Post Office Square Boston',
  'Old South Meeting House Boston',
  "King's Chapel & Burying Ground Boston",
  'Old State House Boston',
  'Faneuil Hall Marketplace Boston',
  "Copp's Hill Burying Ground Boston",
  'Old North Church Boston',
  'Paul Revere Mall Boston',
  'Paul Revere House Boston',
  'Waterfront Boston',
  'Trinity Church Boston',
  'Copley Square Boston',
  'Newbury Street Boston',
  'Commonwealth Avenue Boston',
  'John F. Kennedy Library & Museum Boston',
  'Isabella Stewart Gardner Museum Boston',
  'Museum of Fine Arts Boston',
  'Cambridge Boston',
  'Charlestown Boston',
  'Salem Massachusetts',
  'Lowell Massachusetts',
  'Concord Massachusetts',
  'Plymouth Massachusetts',
  'Cape Cod Massachusetts',
  'Sturbridge Massachusetts',
  'The Berkshires Massachusetts',
  'Providence Rhode Island',
  'Newport Rhode Island',
  'South County Beaches Rhode Island',
  'Block Island Rhode Island',
  'Hartford Connecticut',
  'Litchfield Connecticut',
  'Connecticut River Valley Connecticut',
  'New Haven Connecticut',
  'Connecticut Coast Connecticut',
  'Green Mountain National Forest Vermont',
  'Manchester Vermont',
  'Killington Vermont',
  'Woodstock Vermont',
  'Shelburne Museum & Farms Vermont',
  'Burlington Vermont',
  'Lake Champlain Vermont',
  'Stowe Vermont',
  "Ben & Jerry's Ice Cream Factory Vermont",
  'Bretton Woods New Hampshire',
  'Franconia Notch New Hampshire',
  'White Mountain National Forest New Hampshire',
  'Lake Winnipesaukee New Hampshire',
  'Canterbury Shaker Village New Hampshire',
  'Concord New Hampshire',
  'Manchester New Hampshire',
  'Portsmouth New Hampshire',
  'Portland Maine',
  'The Kennebunks Maine',
  'Penobscot Bay Maine',
  'Acadia National Park Maine',
  'Campobello Island Maine',
  'Sugarloaf Maine',
  'Bethel Maine',
  'United States Capitol Washington, DC',
  'Library of Congress Washington, DC',
  'US Supreme Court Washington, DC',
  'National Air & Space Museum Washington, DC',
  'National Gallery of Art Washington, DC',
  'National Museum of Natural History Washington, DC',
  'National Museum of African Art Washington, DC',
  'National Museum of American History Washington, DC',
  'Smithsonian American Art Museum & National Portrait Gallery Washington, DC',
  'Washington Monument Washington, DC',
  'National World War II Memorial Washington, DC',
  'United States Holocaust Memorial Museum Washington, DC',
  'Jefferson Memorial Washington, DC',
  'Franklin D. Roosevelt Memorial Washington, DC',
  'Martin Luther King, Jr. Memorial Washington, DC',
  'Lincoln Memorial Washington, DC',
  'Vietnam Veterans Memorial Washington, DC',
  'The White House Washington, DC',
  'Renwick Gallery Washington, DC',
  'Corcoran Gallery of Art Washington, DC',
  'The Kennedy Center Washington, DC',
  'Watergate Complex Washington, DC',
  'Georgetown Washington, DC',
  'Alexandria Virginia',
  "George Washington's Mount Vernon Estate Virginia",
  'Fredericksburg Virginia',
  'Colonial Williamsburg Virginia',
  'Jamestown & Yorktown Virginia',
  'Norfolk Virginia',
  'Richmond Virginia',
  'Chincoteague Virginia',
  'Charlottesville Virginia',
  'Appomattox Court House National Historical Park Virginia',
  'Blue Ridge Parkway Virginia',
  'Skyline Drive Virginia',
  'Monongahela National Forest West Virginia',
  'New River Gorge National River West Virginia',
  'Harpers Ferry West Virginia',
  'Antietam National Battlefield Maryland',
  'Frederick Maryland',
  'Baltimore Maryland',
  'Annapolis Maryland',
  'North Bay Maryland',
  'St. Michaels Maryland',
  'Easton Maryland',
  'Crisfield Maryland',
  'Salisbury Maryland',
  'Ocean City Maryland',
  'Wilmington Delaware',
  'Winterthur Delaware',
  'Hagley Museum/ Eleutherian Mills Delaware',
  'Nemours Mansion & Gardens Delaware',
  'New Castle Delaware',
  'Lewes Delaware',
  'Rehoboth Beach Delaware',
  'Research Triangle Region North Carolina',
  'Winston-Salem North Carolina',
  'Blue Ridge Parkway North Carolina',
  'Asheville North Carolina',
  'Charlotte North Carolina',
  'Outer Banks North Carolina',
  'Roanoke Island North Carolina',
  'Beaufort North Carolina',
  'Charleston South Carolina',
  'Columbia South Carolina',
  'Myrtle Beach South Carolina',
  'Georgetown South Carolina',
  'Coastal Islands South Carolina',
  'Savannah Georgia',
  'Golden Isles Georgia',
  'Okefenokee Swamp National Wildlife Refuge Georgia',
  'Americus Georgia',
  'Macon Georgia',
  'Athens Georgia',
  'Dahlonega Georgia',
  'Stone Mountain Park Georgia',
  'Atlanta Georgia',
  'Great Smoky Mountains National Park Tennessee',
  'Chattanooga Tennessee',
  'Nashville Tennessee',
  'Memphis Tennessee',
  'Cumberland Gap National Historic Park Kentucky',
  'Mammoth Cave National Park Kentucky',
  'Berea Kentucky',
  'Daniel Boone National Forest Kentucky',
  'Lexington Kentucky',
  'Harrodsburg Kentucky',
  'Hodgenville Kentucky',
  'Bardstown Kentucky',
  'Louisville Kentucky',
  'South Beach Miami',
  'Holocaust Memorial Miami',
  'Bass Museum of Art Miami',
  'Biscayne Bay Boat Trips Miami',
  'Museum Park Miami',
  'Miami-Dade Cultural Center Miami',
  'Downtown Miami',
  'Little Havana Miami',
  'Coral Gables Miami',
  'Biltmore Hotel Miami',
  'Venetian Pool Miami',
  'Coconut Grove Village Miami',
  'Vizcaya Miami',
  'North Beaches Miami',
  'Ancient Spanish Monastery Miami',
  'Key Biscayne Miami',
  'Fairchild Tropical Botanic Garden Miami',
  'Zoo Miami Miami',
  'Wings Over Miami Miami',
  'Fort Lauderdale The Gold & Treasure Coasts',
  'Boca Raton The Gold & Treasure Coasts',
  'Arthur R. Marshall Loxahatchee National Wildlife Refuge The Gold & Treasure Coasts',
  'Palm Beach The Gold & Treasure Coasts',
  'Cocoa Beach Orlando & the Space Coast',
  'Kennedy Space Center Orlando & the Space Coast',
  'Canaveral National Seashore & Merritt Island Orlando & the Space Coast',
  'Walt Disney World® Resort Orlando & the Space Coast',
  'Universal Orlando® Resort Orlando & the Space Coast',
  'SeaWorld® Orlando & Discovery Cove® Orlando & the Space Coast',
  'Orlando Orlando & the Space Coast',
  'Winter Park Orlando & the Space Coast',
  'International Drive Orlando & the Space Coast',
  'LEGOLAND® Florida Resort Orlando & the Space Coast',
  'Disney Wilderness Preserve Orlando & the Space Coast',
  'Daytona Beach The Northeast',
  'St. Augustine The Northeast',
  'Fernandina Beach The Northeast',
  'Ocala National Forest The Northeast',
  'Tallahassee The Panhandle',
  'Pensacola The Panhandle',
  'Apalachicola The Panhandle',
  'Tampa The Gulf Coast',
  'St. Petersburg The Gulf Coast',
  'Sarasota The Gulf Coast',
  'Lee Island Coast The Gulf Coast',
  'Big Cypress Swamp The Everglades & the Keys',
  'Everglades National Park The Everglades & the Keys',
  'Biscayne National Park The Everglades & the Keys',
  'The Keys The Everglades & the Keys',
  'Key West The Everglades & the Keys',
  'Old US Mint New Orleans',
  'Old Ursuline Convent New Orleans',
  'French Market New Orleans',
  'Café du Monde New Orleans',
  'Jackson Square New Orleans',
  'St. Louis Cathedral, Cabildo, & Presbytère New Orleans',
  'Washington Artillery Park and Moonwalk New Orleans',
  'St. Louis Cemetery #1 New Orleans',
  'Hermann-Grima Historic House New Orleans',
  'Bourbon Street New Orleans',
  'Royal Street New Orleans',
  'Steamboat Natchez New Orleans',
  'Custom House New Orleans',
  'Audubon Aquarium of the Americas New Orleans',
  'Mardi Gras World New Orleans',
  'Outlet Collection at Riverwalk New Orleans',
  'National WWII Museum New Orleans',
  'Garden District New Orleans',
  'City Park New Orleans',
  'Plantation Alley Louisiana',
  'Baton Rouge Louisiana',
  'Lafayette Louisiana',
  'Bayou Teche Louisiana',
  'Natchitoches Louisiana',
  'Shreveport Louisiana',
  'Little Rock Arkansas',
  'Hot Springs Arkansas',
  'Mountain View Arkansas',
  'Eureka Springs Arkansas',
  'Clarksdale Mississippi',
  'Oxford Mississippi',
  'Tupelo Mississippi',
  'Vicksburg National Military Park Mississippi',
  'Jackson Mississippi',
  'Natchez Trace Parkway Mississippi',
  'Natchez Mississippi',
  'Gulf Coast Mississippi',
  'Mobile Alabama',
  'Selma Alabama',
  'Montgomery Alabama',
  'Tuskegee Alabama',
  'Birmingham Alabama',
  'Huntsville Alabama',
  'Chicago History Museum Chicago',
  'Newberry Library Chicago',
  'Magnificent Mile Chicago',
  'John Hancock Center Chicago',
  'Navy Pier Chicago',
  "Chicago Children's Museum Chicago",
  'Millennium Park Chicago',
  'Art Institute of Chicago Chicago',
  'Willis Tower Chicago',
  'The Loop Chicago',
  'South Loop Chicago',
  'Museum Campus Chicago',
  'Museum of Science & Industry Chicago',
  'University of Chicago',
  'DuSable Museum of African American History Chicago',
  'Lincoln Park Zoo Chicago',
  'Oak Park Chicago',
  'Rockford Illinois',
  'Galena Illinois',
  'Springfield Illinois',
  'Southern Illinois',
  'New Harmony Indiana',
  'Bloomington Indiana',
  'Indiana Dunes National Lakeshore Indiana',
  'South Bend Indiana',
  'Shipshewana Indiana',
  'Fort Wayne Indiana',
  'Indianapolis Indiana',
  'Columbus Indiana',
  'Ohio River Valley Indiana',
  'Cincinnati Ohio',
  'Dayton Ohio',
  'Serpent Mound Ohio',
  'Hopewell Culture National Historical Park Ohio',
  'Columbus Ohio',
  'Berlin Ohio',
  'Cleveland Ohio',
  'Lake Erie Islands Ohio',
  'Sandusky Ohio',
  'Toledo Ohio',
  'Detroit Michigan',
  'Ann Arbor Michigan',
  'Lansing Michigan',
  'Grand Rapids Michigan',
  'Lake Michigan Shore Michigan',
  'Mackinac Island Michigan',
  'Upper Peninsula Michigan',
  'Milwaukee Wisconsin',
  'Door County Wisconsin',
  'Wisconsin Dells Wisconsin',
  'Baraboo Wisconsin',
  'Madison Wisconsin',
  'Spring Green Wisconsin',
  'La Crosse Wisconsin',
  'Apostle Islands Wisconsin',
  'Minneapolis & St. Paul Minnesota',
  'Mississippi River Towns Minnesota',
  'Rochester Minnesota',
  'Pipestone National Monument Minnesota',
  'Brainerd Lakes Area Minnesota',
  'Duluth Minnesota',
  'Iron Range Minnesota',
  'Boundary Waters Canoe Area Wilderness Minnesota',
  'Voyageurs National Park Minnesota',
  'Headwaters of Mississippi River Minnesota',
  'Grand Forks North Dakota',
  'Devils Lake North Dakota',
  'Washburn North Dakota',
  'Theodore Roosevelt National Park North Dakota',
  'Bismarck & Mandan North Dakota',
  'Fargo North Dakota',
  'Mitchell South Dakota',
  'Pierre South Dakota',
  'Badlands National Park South Dakota',
  'Wall South Dakota',
  'Pine Ridge Reservation South Dakota',
  'Black Hills South Dakota',
  'Chadron Nebraska',
  'Ogallala Nebraska',
  'North Platte Nebraska',
  'Lincoln Nebraska',
  'Nebraska City Nebraska',
  'Omaha Nebraska',
  'Sioux City Iowa',
  'Des Moines Iowa',
  'Amana Colonies Iowa',
  'Cedar Rapids Iowa',
  'Dubuque Iowa',
  'Quad Cities (Davenport) Iowa',
  'Iowa City Iowa',
  'St. Louis Missouri',
  'Jefferson City Missouri',
  'Branson Missouri',
  'Kansas City Missouri',
  'St. Joseph Missouri',
  'Lawrence Kansas',
  'Topeka Kansas',
  'Flint Hills Kansas',
  'Wichita Kansas',
  'Dodge City Kansas',
  'Bartlesville Oklahoma',
  'Tulsa Oklahoma',
  'Tahlequah Oklahoma',
  'Oklahoma City Oklahoma',
  'Dallas Texas',
  'Fort Worth Texas',
  'Austin Texas',
  'Fredericksburg Texas',
  'Kerrville Texas',
  'New Braunfels Texas',
  'San Antonio Texas',
  'Houston Texas',
  'Big Thicket National Preserve Texas',
  'Galveston Texas',
  'Aransas National Wildlife Refuge Texas',
  'Corpus Christi Texas',
  'Padre Island National Seashore Texas',
  'Laredo Texas',
  'Rio Grande Valley Texas',
  'Big Bend National Park Texas',
  'Fort Davis Texas',
  'El Paso Texas',
  'Guadalupe Mountains National Park Texas',
  'Lubbock Texas',
  'Canyon Texas',
  'Amarillo Texas',
  'Abilene Texas',
  'Las Vegas Nevada',
  'Carson City Nevada',
  'Virginia City Nevada',
  'Reno Nevada',
  'Great Basin National Park Nevada',
  'Salt Lake City Utah',
  'Great Salt Lake Utah',
  'Park City Utah',
  'Timpanogos Cave National Monument Utah',
  'Arches National Park Utah',
  'Moab Utah',
  'Canyonlands National Park Utah',
  'Green River Utah',
  'Hovenweep National Monument Utah',
  'Lake Powell & Glen Canyon National Recreation Area Utah',
  'Capitol Reef National Park Utah',
  'Grand Staircase–Escalante National Monument Utah',
  'Bryce Canyon National Park Utah',
  'Cedar City Utah',
  'Zion National Park Utah',
  'Lake Havasu City Arizona',
  'Flagstaff Arizona',
  'Heart of Arizona Tour Arizona',
  'Phoenix Arizona',
  'Tucson Arizona',
  'Nogales Arizona',
  'Bisbee Arizona',
  'Amerind Foundation Arizona',
  'Petrified Forest National Park Arizona',
  'Window Rock Arizona',
  'Hopi Cultural Center Arizona',
  'Tuba City Arizona',
  'Grand Canyon Arizona',
  'Navajo National Monument Arizona',
  'Monument Valley Arizona',
  'Canyon de Chelly National Monument Arizona',
  'Chaco Culture National Historical Park New Mexico',
  'Taos New Mexico',
  'Northern Pueblos Tour New Mexico',
  'Santa Fe New Mexico',
  'Albuquerque New Mexico',
  'Roswell New Mexico',
  'Carlsbad Caverns National Park New Mexico',
  'White Sands National Monument New Mexico',
  'Gila Cliff Dwellings National Monument New Mexico',
  "Coeur d'Alene Idaho",
  'Hells Canyon National Recreation Area Idaho',
  'Salmon Idaho',
  'Sawtooth National Recreation Area Idaho',
  'Boise Idaho',
  'Sun Valley Idaho',
  'Three Island Crossing State Park Idaho',
  'Bruneau Dunes State Park Idaho',
  'Twin Falls Idaho',
  'Craters of the Moon National Monument Idaho',
  'Idaho Falls Idaho',
  'Big Hole National Battlefield Montana',
  'Missoula Montana',
  'Flathead Valley Montana',
  'Glacier National Park Montana',
  'Great Falls Montana',
  'Helena Montana',
  'Butte Montana',
  'Bozeman Montana',
  'Virginia City Montana',
  'Billings Montana',
  'Little Bighorn Battlefield National Monument Montana',
  'Cody Wyoming',
  'Yellowstone National Park Wyoming',
  'Jackson Wyoming',
  'Grand Teton National Park Wyoming',
  'Bighorn Mountains Wyoming',
  "Devil's Tower National Monument Wyoming",
  'Casper Wyoming',
  'Guernsey Wyoming',
  'Laramie Wyoming',
  'Cheyenne Wyoming',
  'Denver Colorado',
  'Boulder Colorado',
  'Golden Colorado',
  'Idaho Springs & Georgetown Colorado',
  'Rocky Mountain National Park Colorado',
  'Manitou Springs Colorado',
  'Colorado Springs Colorado',
  'Cripple Creek Colorado',
  'Cañon City Colorado',
  'Colorado Ski Resorts Colorado',
  'Great Sand Dunes National Park & Preserve Colorado',
  'Durango Colorado',
  'Mesa Verde National Park Colorado',
  'Ouray Colorado',
  'Black Canyon of the Gunnison National Park Colorado',
  'Colorado National Monument Colorado',
  'Seattle Washington',
  'Olympic Peninsula Washington',
  'Port Townsend Washington',
  'Bellingham Washington',
  'San Juan Islands Washington',
  'North Cascades Highway Washington',
  'Lake Chelan Washington',
  'Leavenworth Washington',
  'Spokane Washington',
  'Walla Walla Washington',
  'Yakima Valley Washington',
  'Maryhill Washington',
  'Mount Rainier National Park Washington',
  'Tacoma Washington',
  'Olympia Washington',
  'Mount St. Helens National Volcanic Monument Washington',
  'Fort Vancouver National Historic Site Washington',
  'Portland Oregon',
  'Columbia River Gorge Oregon',
  'Mount Hood Oregon',
  'Astoria Oregon',
  'Oregon Coast Oregon',
  'Salem Oregon',
  'Eugene Oregon',
  'Madras & Warm Springs Oregon',
  'Sisters Oregon',
  'Bend Oregon',
  'Newberry National Volcanic Monument Oregon',
  'Crater Lake National Park Oregon',
  'Oregon Caves National Monument Oregon',
  'Ashland Oregon',
  'Steens Mountain Oregon',
  'Malheur National Wildlife Refuge Oregon',
  'John Day Fossil Beds National Monument Oregon',
  'Pendleton Oregon',
  'Wallowa Mountains Oregon',
  "Hell's Canyon National Recreation Area Oregon",
  'The Getty Center Los Angeles',
  'Santa Monica Los Angeles',
  'Venice Los Angeles',
  'Museum of Tolerance Los Angeles',
  'Westwood & UCLA Los Angeles',
  'The Golden Triangle Los Angeles',
  'Sunset Boulevard Los Angeles',
  'Mulholland Drive Los Angeles',
  'Hollywood Boulevard Los Angeles',
  'Hollywood Bowl Los Angeles',
  'Farmers Market Los Angeles',
  'Miracle Mile Los Angeles',
  'Exposition Park & University of Southern California Los Angeles',
  'Los Angeles Central Library Los Angeles',
  'Los Angeles City Hall Los Angeles',
  'Music Center Los Angeles',
  'Grand Central Market Los Angeles',
  'Little Tokyo Los Angeles',
  'Museum of Contemporary Art Los Angeles',
  'El Pueblo Los Angeles',
  'Lummis Home and Garden Los Angeles',
  'The Autry Los Angeles',
  'Griffith Park Los Angeles',
  'Hollywood Sign Los Angeles',
  'Universal StudiosSM Los Angeles',
  'Malibu Los Angeles',
  'Pasadena Los Angeles',
  'Watts Towers Los Angeles',
  'Long Beach Los Angeles',
  "Knott's Berry Farm® Los Angeles",
  'Mission San Juan Capistrano Los Angeles',
  'Newport Beach Los Angeles',
  'Disneyland® Resort Los Angeles',
  'San Diego San Diego County',
  'SeaWorld® San Diego County',
  'La Jolla San Diego County',
  'Tijuana, Mexico San Diego County',
  'Palm Springs The Deserts',
  'Anza-Borrego Desert State Park The Deserts',
  'Salton Sea State Recreation Area The Deserts',
  'Joshua Tree National Park The Deserts',
  'Mojave Desert The Deserts',
  'Death Valley National Park The Deserts',
  'Santa Barbara Central Coast',
  'Channel Islands National Park Central Coast',
  'Lompoc Valley Central Coast',
  'San Luis Obispo Central Coast',
  'Hearst Castle® Central Coast',
  'Big Sur Central Coast',
  'Carmel Central Coast',
  'Monterey Central Coast',
  'Santa Cruz Central Coast',
  'San Francisco Central Coast',
  'Sonoma Valley The Wine Country',
  'Napa Valley The Wine Country',
  'Russian River Valley The Wine Country',
  'Fort Ross State Historic Park The Wine Country',
  'Mendocino The Wine Country',
  'Humboldt Redwoods State Park Northern California',
  'Eureka Northern California',
  'Redwood National Park Northern California',
  'Weaverville Northern California',
  'Mount Shasta Northern California',
  'Lava Beds National Monument Northern California',
  'Lassen Volcanic National Park Northern California',
  'Nevada City The Gold Country',
  'Grass Valley The Gold Country',
  'Marshall Gold Discovery State Park The Gold Country',
  'Sacramento The Gold Country',
  'Highway 49 The Gold Country',
  'Columbia State Historic Park The Gold Country',
  'Lake Tahoe The High Sierras',
  'Yosemite National Park The High Sierras',
  'Eastern Sierras The High Sierras',
  'Sequoia & Kings Canyon National Parks The High Sierras',
  'Financial District San Francisco',
  'Wells Fargo History Museum San Francisco',
  'Yerba Buena Center for the Arts San Francisco',
  'San Francisco Museum of Modern Art San Francisco',
  'Union Square San Francisco',
  'Chinatown San Francisco',
  'Nob Hill San Francisco',
  "Fisherman's Wharf San Francisco",
  'North Beach San Francisco',
  'Alcatraz Island San Francisco',
  'Pacific Heights San Francisco',
  'Asian Art Museum San Francisco',
  'Mission Dolores San Francisco',
  'Haight Ashbury San Francisco',
  'California Academy of Sciences San Francisco',
  'de Young Museum San Francisco',
  'Legion of Honor San Francisco',
  'The Presidio San Francisco',
  'Golden Gate Bridge San Francisco',
  'San Jose San Francisco',
  'Palo Alto San Francisco',
  'Oakland San Francisco',
  'Berkeley San Francisco',
  'Sausalito San Francisco',
  'Muir Woods San Francisco',
  'Ketchikan Alaska',
  'Sitka Alaska',
  'Juneau Alaska',
  'Glacier Bay National Park Alaska',
  'Skagway Alaska',
  'Anchorage Alaska',
  'Valdez Alaska',
  'Seward Alaska',
  'Homer Alaska',
  'Kodiak Island Alaska',
  'Alaska Peninsula Alaska',
  'Aleutian Islands Alaska',
  'Nome Alaska',
  'Fairbanks Alaska',
  'Wrangell-St. Elias National Park Alaska',
  'Denali National Park Alaska',
  "Honolulu O'ahu",
  "Byodo-In Temple O'ahu",
  "Hawai'i's Plantation Village O'ahu",
  "North Shore O'ahu",
  "Kaunakakai Moloka'i & Maui",
  "Kalaupapa National Historical Park Moloka'i & Maui",
  "Lahaina Moloka'i & Maui",
  "Haleakalā National Park Moloka'i & Maui",
  "Hāna Moloka'i & Maui",
  "Hawai'i Volcanoes National Park Hawai'i",
  "Hilo Hawai'i",
  "Pu'uhonua O Hōnaunau National Historical Park Hawai'i",
  "Līhu'e Kaua'i",
  "Kīlauea Point Kaua'i",
  "Waimea Canyon & Kōke'e State Park Kaua'i",
  "Kalalau Trail Kaua'i",
]

export default searchList
